import { Barlow_Condensed } from "next/font/google";

import "@/app/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "cinmax",
  description: "Generated by create next app",
};

export const barlowCondensed = Barlow_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "latin-ext", "vietnamese"],
  variable: "--font-barlow-condensed",
  display: "swap",
});

// This root layout is intentionally minimal now. It used to also render
// <Footer /> after {children}, but that meant the public site footer
// showed up on /admin pages too. The footer moved into
// app/(site)/layout.tsx, which wraps the public pages only —
// app/admin/layout.tsx wraps the admin pages instead.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${barlowCondensed.variable} h-full antialiased`}
    >
      <body
        className={`${barlowCondensed.className} min-h-full flex flex-col bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
